[package]
name = "calmserve"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0"
futures-util = "0.3"
mime_guess = "2.0"
percent-encoding = "2.3"
rcgen = "0.14"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls-webpki-roots-no-provider", "stream"] }
rustls = { version = "0.23", default-features = false, features = ["aws_lc_rs", "std", "tls12"] }
serde_json = "1.0"
tokio = { version = "1.47", features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "signal", "time"] }
twinstar = { git = "https://github.com/panicbit/twinstar", rev = "a93f2c25e3d1d8f9331019a51dfa7cc85fef77a3" }
url = "2.5"

[dev-dependencies]
tempfile = "3.20"
